name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  checkCommits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check commit messages
        uses: GsActions/commit-message-checker@v2
        with:
          pattern: "^(?!WIP).*$"
          error: "The first line cannot start with WIP"
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & test the Gradle project
        run: ./gradlew allTests

      - name: Build & test the Gradle project
        run: ./gradlew :core:allTests :math:allTests :geometry:allTests
        working-directory: ./DevToolkt
