name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  checkCommits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check commit messages
        uses: GsActions/commit-message-checker@v2
        with:
          pattern: "^(?!WIP).*$"
          error: "The first line cannot start with WIP"
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  rootTests:
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      task: 'allTests'

  coreTests:
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      task: ':core:allTests'
      working-dir: './DevToolkt'

  mathTests:
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      task: ':math:allTests'
      working-dir: './DevToolkt'

  geometryTests:
    uses: ./.github/workflows/run-gradle-task.yml
    with:
      task: ':geometry:allTests'
      working-dir: './DevToolkt'
